import Head from "next/head";
import Script from "next/script";
import { Navbar } from "../components/Navbar";
import { Presentation } from "../components/Presentation";
import { Tecnologies } from "../components/Tecnologies";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio Jonathan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/devicons/devicon@v2.15.1/devicon.min.css"
        />
      </Head>

      <main className="main-container">
        <Navbar />

        <Presentation />

        <Tecnologies />
        
      </main>
    </div>
  );
}
