import Head from "next/head";
import Image from "next/image";
import { MainSvg } from "../components/MainSvg";
import { Navbar } from "../components/Navbar";
import { Presentation } from "../components/Presentation";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main-container">
        <Navbar />
        <Presentation /> 
      </main>
    </div>
  );
}
